### ISSUE TITLE
[mat-views] Melhorias v1.1

### ISSUE THREAD

**Issue by JoaoCarabetta** [RJ-SMTR/maestro#126]
- [ ] parametrizar views das dependências temporalmente toda vez que a view materializada rodar @Hellcassius 

- [x] ter a opção de materializar aos poucos, já que grandes intervalos de materialização podem levar muito tempo ou até acabar com os recursos do BQ

- [x] Lidar com streaming inserts usando DML. Error 413: Message: response too large

----------------------------------------------------------------------------------------------------

- [x] materializar tabela se existir view com mesmo nome. 
Talvez criar uma flag `if_exists` para determinar o comportamento de materialização nesses casos.

- [x] materializar tabela se parâmetros (cron, data_range, etc) foram modificados
 Hoje o código só roda a materialização se a query mudou, mas não acompanha mudanças do cron, data_range e outros.

**Comment by gabriel-milan** [comment]
> * ter a opção de materializar aos poucos, já que grandes intervalos de materialização podem levar muito tempo ou até acabar com os recursos do BQ

Agora, nos YAMLs de configuração, o parâmetro `backfill` deve ser configurado da seguinte maneira:

```yaml
# Parâmetros de backfill
backfill:
  # Formato %Y-%m-%d %H:%M:%S
  start_timestamp: "2021-01-01 00:00:00"
  # Intervalo para materialização em lotes
  interval:
    # Aceita múltiplas chaves:
    # seconds, minutes, hours, days
    # ou uma combinação de vários
    days: 1
```

> * Lidar com streaming inserts usando DML. Error 413: Message: response too large

Agora os inserts são feitos através de `INSERT INTO ...`
